name: galflux
channels: [conda-forge]
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - pandas
  - pyyaml
  - astropy
  - astroquery
  - photutils
  - reproject
  - matplotlib
  - requests
  - pytest
  - pip:
    - -e .
