name: galflux
channels: [conda-forge]
dependencies:
  - python>=3.10
  - numpy
  - scipy
  - pandas
  - pyyaml
  - astropy
  - astroquery
  - photutils
  - reproject
  - matplotlib
  - requests
  - pytest
  - pip
  - pip:
      - -e .
